# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_officialclassnames_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RacerId',
            new_name='Racer',
        ),
        migrations.RenameField(
            model_name='laptimes',
            old_name='racerid',
            new_name='racer',
        ),
        migrations.RenameField(
            model_name='singleraceresults',
            old_name='racerid',
            new_name='racer',
        ),
    ]
