# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161009_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportedTrackName',
            new_name='SupportedTrack',
        ),
        migrations.RenameModel(
            old_name='TrackName',
            new_name='Track',
        ),
        migrations.RenameField(
            model_name='singleracedetails',
            old_name='trackkey',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='supportedtrack',
            old_name='trackkey',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='trackname',
            new_name='name',
        ),
    ]
