# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadresults', '0002_singleracedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyuploaderprimaryrecord',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='easyuploadrecord',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='singleracedata',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
