# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadresults', '0003_auto_20160611_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easyuploaderprimaryrecord',
            old_name='trackname',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='easyuploadrecord',
            old_name='trackname',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='singleracedata',
            old_name='trackname',
            new_name='track',
        ),
    ]
